export interface MoonData {
  id: string;
  name: string;
  diameter: number;
  orbitRadius: number;
  orbitSpeed: number;
  rotationSpeed: number;
  color: number;
  description: string;
}

export interface PlanetData {
  id: string;
  name: string;
  description: string;
  diameter: number; // km
  mass: string; // kg in scientific notation
  distanceFromSun: number; // million km
  orbitalPeriod: number; // Earth days
  rotationPeriod: number; // Earth days
  moons: MoonData[];
  temperature: string; // Average temperature
  atmosphere: string;
  texture: string;
  color: string;
  size: number; // Relative size for the 3D model
  orbitSpeed: number; // For animation
  rotationSpeed: number; // For animation
  orbitRadius: number; // For positioning in the 3D scene
  facts: string[];
}

export const planetData: PlanetData[] = [
  {
    id: "mercury",
    name: "Mercury",
    description: "The smallest and innermost planet in the Solar System. Mercury is a rocky planet with a heavily cratered surface similar to the Moon.",
    diameter: 4879,
    mass: "3.3011 × 10^23",
    distanceFromSun: 57.9,
    orbitalPeriod: 88,
    rotationPeriod: 58.6,
    moons: [],
    temperature: "-173°C to 427°C",
    atmosphere: "Minimal - Sodium, Potassium, Oxygen",
    texture: "/textures/mercury.jpg",
    color: "#A0522D",
    size: 0.38,
    orbitSpeed: 0.04,
    rotationSpeed: 0.0017,
    orbitRadius: 5,
    facts: [
      "Mercury has no atmosphere, which means it has no weather.",
      "A day on Mercury (sunrise to sunrise) lasts 176 Earth days.",
      "Mercury has the most eccentric orbit of all the planets.",
      "Mercury has a large iron core that takes up about 60% of its mass."
    ]
  },
  {
    id: "venus",
    name: "Venus",
    description: "The second planet from the Sun and Earth's closest planetary neighbor. Venus has a thick toxic atmosphere and experiences extreme surface temperatures.",
    diameter: 12104,
    mass: "4.8675 × 10^24",
    distanceFromSun: 108.2,
    orbitalPeriod: 225,
    rotationPeriod: -243, // Negative indicates retrograde rotation
    moons: [],
    temperature: "462°C",
    atmosphere: "Dense - Carbon Dioxide, Nitrogen, Sulfuric Acid",
    texture: "/textures/venus.jpg",
    color: "#DEB887",
    size: 0.95,
    orbitSpeed: 0.015,
    rotationSpeed: -0.0004,
    orbitRadius: 7,
    facts: [
      "Venus rotates in the opposite direction to most planets.",
      "A day on Venus is longer than its year.",
      "Venus is the hottest planet in our solar system.",
      "The atmospheric pressure on Venus is 92 times greater than Earth's."
    ]
  },
  {
    id: "earth",
    name: "Earth",
    description: "Our home planet and the only known celestial body to harbor life. Earth has liquid water, an oxygen-rich atmosphere, and a protective magnetic field.",
    diameter: 12742,
    mass: "5.9724 × 10^24",
    distanceFromSun: 149.6,
    orbitalPeriod: 365.25,
    rotationPeriod: 1,
    moons: [
      {
        id: 'moon',
        name: 'Moon',
        diameter: 3474,
        orbitRadius: 5,
        orbitSpeed: 0.5,
        rotationSpeed: 0.1,
        color: 0xE6E6FA,
        description: 'Earth\'s only natural satellite.'
      }
    ],
    temperature: "-88°C to 58°C",
    atmosphere: "Nitrogen, Oxygen, Argon, Carbon Dioxide",
    texture: "/textures/earth.jpg",
    color: "#4169E1",
    size: 1,
    orbitSpeed: 0.01,
    rotationSpeed: 0.01,
    orbitRadius: 10,
    facts: [
      "Earth is the only planet not named after a god.",
      "Earth's atmosphere protects us from meteoroids and radiation from the Sun.",
      "71% of Earth's surface is covered in water.",
      "Earth's magnetic field is generated by the movement of molten iron in its outer core."
    ]
  },
  {
    id: "mars",
    name: "Mars",
    description: "The fourth planet from the Sun, often called the 'Red Planet' due to its reddish appearance. Mars has polar ice caps, seasons, and evidence of ancient rivers and lakes.",
    diameter: 6779,
    mass: "6.4171 × 10^23",
    distanceFromSun: 227.9,
    orbitalPeriod: 687,
    rotationPeriod: 1.03,
    moons: [
      {
        id: 'phobos',
        name: 'Phobos',
        diameter: 22.2,
        orbitRadius: 3,
        orbitSpeed: 1.5,
        rotationSpeed: 0.2,
        color: 0x8B4513,
        description: 'The larger and inner moon of Mars.'
      },
      {
        id: 'deimos',
        name: 'Deimos',
        diameter: 12.6,
        orbitRadius: 4,
        orbitSpeed: 0.8,
        rotationSpeed: 0.1,
        color: 0xA0522D,
        description: 'The smaller and outer moon of Mars.'
      }
    ],
    temperature: "-153°C to 20°C",
    atmosphere: "Thin - Carbon Dioxide, Nitrogen, Argon",
    texture: "/textures/mars.jpg",
    color: "#CD853F",
    size: 0.53,
    orbitSpeed: 0.008,
    rotationSpeed: 0.009,
    orbitRadius: 15,
    facts: [
      "Mars has the largest dust storms in the solar system.",
      "Mars has the tallest mountain in the solar system, Olympus Mons.",
      "The red color of Mars comes from iron oxide (rust) on its surface.",
      "Mars has frozen water at its poles and possibly liquid water underground."
    ]
  },
  {
    id: "jupiter",
    name: "Jupiter",
    description: "The largest planet in our Solar System, a gas giant with a distinctive system of rings and a Great Red Spot. Jupiter has a strong magnetic field and numerous moons.",
    diameter: 139820,
    mass: "1.8982 × 10^27",
    distanceFromSun: 778.5,
    orbitalPeriod: 4333,
    rotationPeriod: 0.41,
    moons: [
      {
        id: 'io',
        name: 'Io',
        diameter: 3643,
        orbitRadius: 8,
        orbitSpeed: 2.5,
        rotationSpeed: 0.3,
        color: 0xFFD700,
        description: 'The most volcanically active body in the solar system.'
      },
      {
        id: 'europa',
        name: 'Europa',
        diameter: 3122,
        orbitRadius: 10,
        orbitSpeed: 2.0,
        rotationSpeed: 0.2,
        color: 0xF0F8FF,
        description: 'A moon with a subsurface ocean.'
      },
      {
        id: 'ganymede',
        name: 'Ganymede',
        diameter: 5268,
        orbitRadius: 12,
        orbitSpeed: 1.5,
        rotationSpeed: 0.2,
        color: 0xD3D3D3,
        description: 'The largest moon in the solar system.'
      },
      {
        id: 'callisto',
        name: 'Callisto',
        diameter: 4821,
        orbitRadius: 14,
        orbitSpeed: 1.2,
        rotationSpeed: 0.1,
        color: 0x808080,
        description: 'The most heavily cratered object in the solar system.'
      }
    ],
    temperature: "-145°C",
    atmosphere: "Hydrogen, Helium, Methane, Ammonia",
    texture: "/textures/jupiter.jpg",
    color: "#DAA520",
    size: 11.2,
    orbitSpeed: 0.004,
    rotationSpeed: 0.024,
    orbitRadius: 25,
    facts: [
      "Jupiter has the shortest day of all the planets.",
      "The Great Red Spot is a storm that has been raging for at least 400 years.",
      "Jupiter's magnetic field is 14 times stronger than Earth's.",
      "Jupiter has a faint ring system, discovered in 1979."
    ]
  },
  {
    id: "saturn",
    name: "Saturn",
    description: "The sixth planet from the Sun and the second-largest in the Solar System. Saturn is known for its prominent ring system and has numerous moons.",
    diameter: 116460,
    mass: "5.6834 × 10^26",
    distanceFromSun: 1434,
    orbitalPeriod: 10759,
    rotationPeriod: 0.44,
    moons: [
      {
        id: 'titan',
        name: 'Titan',
        diameter: 5149,
        orbitRadius: 10,
        orbitSpeed: 1.8,
        rotationSpeed: 0.2,
        color: 0xDEB887,
        description: 'The only moon with a substantial atmosphere.'
      },
      {
        id: 'enceladus',
        name: 'Enceladus',
        diameter: 504,
        orbitRadius: 6,
        orbitSpeed: 2.2,
        rotationSpeed: 0.3,
        color: 0xF5F5F5,
        description: 'A moon with geysers of water ice.'
      },
      {
        id: 'mimas',
        name: 'Mimas',
        diameter: 396,
        orbitRadius: 4,
        orbitSpeed: 2.5,
        rotationSpeed: 0.3,
        color: 0xD2B48C,
        description: 'Known as the Death Star moon due to its large crater.'
      }
    ],
    temperature: "-178°C",
    atmosphere: "Hydrogen, Helium, Methane",
    texture: "/textures/saturn.jpg",
    color: "#F4A460",
    size: 9.45,
    orbitSpeed: 0.002,
    rotationSpeed: 0.022,
    orbitRadius: 40,
    facts: [
      "Saturn's rings are made mostly of ice particles, with a small amount of rocky debris and dust.",
      "Saturn has the lowest density of all the planets in our solar system - it would float in water.",
      "Saturn's moon Titan is the second-largest moon in the solar system and has a thick atmosphere.",
      "The day Saturday was named after Saturn."
    ]
  },
  {
    id: "uranus",
    name: "Uranus",
    description: "The seventh planet from the Sun, an ice giant with a pale blue-green color due to methane in its atmosphere. Uranus rotates on its side, giving it extreme seasons.",
    diameter: 50724,
    mass: "8.6810 × 10^25",
    distanceFromSun: 2871,
    orbitalPeriod: 30687,
    rotationPeriod: -0.72, // Negative indicates retrograde rotation
    moons: [
      {
        id: 'titania',
        name: 'Titania',
        diameter: 1578,
        orbitRadius: 8,
        orbitSpeed: 1.5,
        rotationSpeed: 0.2,
        color: 0xcccccc,
        description: 'The largest moon of Uranus.'
      },
      {
        id: 'oberon',
        name: 'Oberon',
        diameter: 1523,
        orbitRadius: 10,
        orbitSpeed: 1.2,
        rotationSpeed: 0.1,
        color: 0x999999,
        description: 'The second-largest moon of Uranus.'
      },
      {
        id: 'umbriel',
        name: 'Umbriel',
        diameter: 1169,
        orbitRadius: 6,
        orbitSpeed: 1.8,
        rotationSpeed: 0.2,
        color: 0x888888,
        description: 'The darkest moon of Uranus.'
      }
    ],
    temperature: "-224°C",
    atmosphere: "Hydrogen, Helium, Methane",
    texture: "/textures/uranus.jpg",
    color: "#87CEEB",
    size: 4,
    orbitSpeed: 0.0007,
    rotationSpeed: -0.014,
    orbitRadius: 55,
    facts: [
      "Uranus rotates on its side with an axial tilt of 98 degrees.",
      "Uranus was the first planet discovered with a telescope.",
      "Uranus has 13 known rings, which are dark and difficult to see.",
      "The atmosphere of Uranus contains 'ices' such as water, ammonia, and methane."
    ]
  },
  {
    id: "neptune",
    name: "Neptune",
    description: "The eighth and farthest known planet from the Sun, an ice giant similar to Uranus. Neptune has the strongest winds in the Solar System and a Great Dark Spot.",
    diameter: 49244,
    mass: "1.0243 × 10^26",
    distanceFromSun: 4495,
    orbitalPeriod: 60190,
    rotationPeriod: 0.67,
    moons: [
      {
        id: 'triton',
        name: 'Triton',
        diameter: 2707,
        orbitRadius: 8,
        orbitSpeed: 1.6,
        rotationSpeed: 0.2,
        color: 0xffffff,
        description: 'The largest moon of Neptune.'
      },
      {
        id: 'proteus',
        name: 'Proteus',
        diameter: 420,
        orbitRadius: 6,
        orbitSpeed: 1.9,
        rotationSpeed: 0.3,
        color: 0xcccccc,
        description: 'The second-largest moon of Neptune.'
      },
      {
        id: 'nereid',
        name: 'Nereid',
        diameter: 340,
        orbitRadius: 12,
        orbitSpeed: 1.0,
        rotationSpeed: 0.1,
        color: 0x999999,
        description: 'A moon with a highly eccentric orbit.'
      }
    ],
    temperature: "-218°C",
    atmosphere: "Hydrogen, Helium, Methane",
    texture: "/textures/neptune.jpg",
    color: "#1E90FF",
    size: 3.88,
    orbitSpeed: 0.0005,
    rotationSpeed: 0.015,
    orbitRadius: 70,
    facts: [
      "Neptune was predicted to exist through mathematical calculations before it was discovered.",
      "Neptune has the strongest winds in the solar system, reaching up to 2,100 km/h.",
      "Neptune's moon Triton orbits the planet in the opposite direction to Neptune's rotation.",
      "Neptune has only been visited by one spacecraft, Voyager 2 in 1989."
    ]
  }
];

export const getSunData = () => {
  return {
    id: "sun",
    name: "Sun",
    description: "The star at the center of our Solar System. The Sun is a nearly perfect sphere of hot plasma that provides the energy that sustains life on Earth.",
    diameter: 1392700,
    mass: "1.9885 × 10^30",
    distanceFromSun: 0,
    orbitalPeriod: 0,
    rotationPeriod: 27,
    moons: [],
    temperature: "5,500°C (surface), 15,000,000°C (core)",
    atmosphere: "Hydrogen, Helium",
    texture: "/textures/sun.jpg",
    color: "#FFD700",
    size: 109, // Relative to Earth
    orbitSpeed: 0,
    rotationSpeed: 0.004,
    orbitRadius: 0,
    facts: [
      "The Sun accounts for 99.86% of the mass in the solar system.",
      "The Sun is about 4.6 billion years old.",
      "The Sun converts about 600 million tons of hydrogen into helium every second.",
      "Light from the Sun takes about 8 minutes to reach Earth."
    ]
  };
};

export const getPlanetById = (id: string): PlanetData | undefined => {
  if (id === "sun") return getSunData() as PlanetData;
  return planetData.find(planet => planet.id === id);
};